version: "2"
services:

  db:
    container_name: reto1db
    build: ./DB
    networks: ["vnet"]
    ports:
      - 3306:3306
    expose:
      - 3306
    environment: 
      MYSQL_ROOT_PASSWORD: passwd

  coordinator-1:
    container_name: coordinator-1
    networks: ["vnet"]
    depends_on:
      - db
    links:
      - db:reto1db
    hostname: coordinator-1.vnet
    image: reto1prestodb
    ports: 
      - 8080:8080
    environment:
      - PRESTO_JVM_MAX_HEAP=512M
      - PRESTO_QUERY_MAX_MEMORY=1GB
      - PRESTO_QUERY_MAX_MEMORY_PER_NODE=256MB
      - TERM=xterm
    command: coordinator
      
  worker-1:
    container_name: worker-1
    networks: ["vnet"]
    depends_on:
      - db
    links:
      - db:reto1db
    hostname: worker-1.vnet
    image: reto1prestodb
    depends_on: ["coordinator-1"]
    environment:
      - PRESTO_JVM_MAX_HEAP=512M
      - PRESTO_QUERY_MAX_MEMORY=1GB
      - PRESTO_QUERY_MAX_MEMORY_PER_NODE=256MB
      - TERM=xterm      
    command: worker

  worker-2:
    container_name: worker-2
    networks: ["vnet"]
    depends_on:
      - db
    links:
      - db:reto1db
    hostname: worker-2.vnet
    image: reto1prestodb
    depends_on: ["coordinator-1"]
    environment:
      - PRESTO_JVM_MAX_HEAP=512M
      - PRESTO_QUERY_MAX_MEMORY=1GB
      - PRESTO_QUERY_MAX_MEMORY_PER_NODE=256MB
      - TERM=xterm      
    command: worker

networks:
  vnet:
    external:
      name: vnet 
